version: '3.9'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    #    network_mode: service:db
    volumes:
      - redis-data:/data
  tiriage-nginx:
    image: nginx
    build:
      context: src/nginx
    ports:
      - "8001:80"
    depends_on:
      - triage-portal
    volumes:
      - triage-portal-static:/opt/omega/static
    environment:
      - TRIAGE_PORTAL_HOST=triage-portal
  triage-portal:
    image: omega-triage-portal
    build:
      context: src
    container_name: omega-triage-portal
    depends_on:
      redis:
        condition: service_started
    env_file:
      - ./src/.env-template
    volumes:
      - triage-portal-static:/opt/omega/static

volumes:
  redis-data:
  triage-portal-static:
